### ISSUE TITLE
Why a new node?

### ISSUE THREAD

**Issue by hardillb** [tomjmul/node-red-contrib-fake-wemo#2]
Any reason not to work with the author of the other node to fix that rather than add a new node?

**Comment by tomjmul** [comment]
> Any reason not to work with the author of the other node to fix that rather than add a new node?

For starters, I offered to submit a PR but the author didn't reply for months. For seconds, why a new anything? This is a completely different implementation, use it if you want, stick to the original if you want. It's a free world
