### ISSUE TITLE
Strange behaviour from alexa app (android)

### ISSUE THREAD

**Issue by DENightOne** [tomjmul/node-red-contrib-fake-wemo#6]
Hi again,  When i use the alexa app on an android phone to switch the node on, it shows on for a couple of seconds then status reverts back to off....If I look at the node in node-red I see that the node has a green on status and the node is actually on... to turn the node off I have to click "on" again on the app and very quickly click it to turn off again.  I have not restarted node-red so this is not initial state. If i use voice to turn on the node.... the app display show that the switch is off....even though its actually on.

**Comment by tomjmul** [comment]
I've tried to reproduce this issue on IOS and I can't. I don't have any android devices to try with. The IOS Alexa app reports the state correctly and the state icon in the editor seems to work correctly. 

I'm actually thinking of removing the state reporting functionality from the next version of the node. On reflection, I just don't think it's all that useful or indeed can ever be that reliable. Maybe state reporting would be better broken out into separate node with an input to set the state?

**Comment by DENightOne** [comment]
Some more info:  I have noticed that the state file is not updating... my state file (get-binary-state.hbs) is not updating..built a new node red install and it fails on both... the file reads : <BinaryState>{{state}}</BinaryState> so its node writing the state into the file ...If I manually change the state in the file to <BinaryState>1</BinaryState> or <BinaryState>0</BinaryState> then the app shows the appropriate state/status....  I personally think that state of switch is very important as I run outside water pumps off the node.... I can say to alexa turn on and off and it works fine...but most times are cannot see or hear the pump running so I would rely on at app telling me the state/status.

**Comment by tomjmul** [comment]
When you think about it, the node isn't really telling you the state at all, it's just telling you the last on/off command that it executed. That is why I think, possibly another node type might be best for a true closed feedback loop if you can get the real state fed into it from some other process. The poor man's option would be to just feed the last command from this node into the state node for the current functionality.

**Comment by DENightOne** [comment]
Have discovered why its behaving the way it is.... when you set the binary state in sets it only for the node (meaning turns on or off).... when alexa app "asks/requests" for the status (which it does every second) then it always returns what you have set in the initial state regardless of what the current state is....   I changed a few lines of code so that it will report the current state and the alexa app will always show the current state  (if node red is restarted it defaults back to off for safety).

I am only a hobby coder and have zero knowledge about coding so I probably created more problems then I solved:  The changes that I made are in bold.

class WemoEmulator extends MeWoDevice {
    constructor(name, responder, logger, initialState = false) {
        super(name, responder);
        this.log = logger;
        this.state = false;
        **this.currentState=false;**
        this.eventEmitter = new EventEmitter();
        this.emit('listening');
    }

Handles a non-discover request
    handleRequest(body, res) {
        const setStateMatch = body.match(SET_BINARY_STATE);
        const getStateMatch = body.match(GET_BINARY_STATE);
        if (setStateMatch) {
            this.emit(setStateMatch[1] === '1' ? 'on' : 'off', this);
            **if(setStateMatch[1]==="1")
            {
                this.currentState=true;
            }
            else{
                this.currentState=false;
            }**
            res.end();
        } else if (getStateMatch) {
            this.stateResponse(res, **this.currentState**);

**Comment by tomjmul** [comment]
Hobby programmer or not, thanks for your help. I'll take a look tomorrow.

Edit:
Just for your own fun, if you want to, this article will teach you how to make a pull request on Github, if you don't already know. It's actually not very difficult and I'll help you out if needed. God loves a hobby coder 😄 

https://help.github.com/en/articles/creating-a-pull-request

**Comment by tomjmul** [comment]
Fixed

**Comment by DENightOne** [comment]
Thanks.....your fix is coded way better then mine 😊    extra star

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
